name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - sit
          - uat
          - prd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: |
        docker build -t spezi-api:latest -f ./src/Dockerfile .
        docker save -o docker-image.tar spezi-api:latest

    - name: Save Docker Image
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: docker-image.tar

  deploy_iac:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Azure CLI
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az bicep install

    - name: Validate Bicep files
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az bicep build --file ./bicep/main.bicep

    - name: Deploy Infrastructure
      id: deploy_infra
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          az group create --name 'rg-${{ github.event.inputs.environment }}-br-speziapi' --location brazilsouth
          az deployment group create --resource-group rg-${{ github.event.inputs.environment }}-br-speziapi --template-file ./bicep/main.bicep --parameters ./bicep/environments/parameters-${{ github.event.inputs.environment }}.json appRegistrationClientId=${{ secrets.AZURE_CLIENT_ID }} --quer
