name: Deploy Infrastructure as Code (IaC) using Bicep

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - sit
          - uat
          - prd

jobs:
  deploy_iac:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Bicep
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az bicep install
          az bicep build --file ./bicep/main.bicep
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          az group create --name 'rg-${{ github.event.inputs.environment }}-br-speziapi' --location brazilsouth
          az deployment group create --resource-group rg-${{ github.event.inputs.environment }}-br-speziapi --template-file ./bicep/main.bicep --parameters ./bicep/environments/parameters-${{ github.event.inputs.environment }}.json